### ISSUE TITLE
Python module error, can't import cli

### ISSUE THREAD

**Issue by 13scoter** [TailorDev/Watson#15]
System: Ubuntu 12.04, python 2.7

Cloned repository, sudo python setup.py install

Successful.

Run "watson help"

and get:
```
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 9, in <module>
    load_entry_point('watson==0.1', 'console_scripts', 'watson')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/watson-0.1-py2.7.egg/watson/__main__.py", line 1, in <module>
    from watson import cli
ImportError: cannot import name cli
```

**Comment by jmaupetit** [comment]
Thank you for the report! I was able to reproduce it in MacOSX 10.10 with python 2.7. This should be fixed now.

**Comment by 13scoter** [comment]
All good now.

**Comment by jmaupetit** [comment]
Perfect. We would love to have your feedback about watson!
