### ISSUE TITLE
Watson config throwing errors

### ISSUE THREAD

**Issue by rejinka** [TailorDev/Watson#158]
Watson version: 1.5.0

While using the example from the docs (https://tailordev.github.io/Watson/user-guide/configuration/#editing), i get following error:

```
$ watson config backend.token 7e329263e329
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.5.0', 'console_scripts', 'watson')()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2652, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in load
    return self.resolve()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/watson/cli.py", line 867, in config
    if not config.has_section(section):
AttributeError: 'Command' object has no attribute 'has_section'
```

**Comment by SpotlightKid** [comment]
It seems commit 844f1b29db827a4774399f55efb8a59cc08fbfe0 (mine 😞) is the culprit here. It changed the `config` variable to `oldconfig` to not clobber the function name (also `config`) but did this only for the first part of the function. So in the second half of the function where `config` is used it now refers to the click `Command` function wrapper instead of `watson.config`.

I'll prepare a PR with a fix.
