### ISSUE TITLE
UnicodeEncodeError when trying to start a task with a name that contains the cedilla character

### ISSUE THREAD

**Issue by renatoliveira** [TailorDev/Watson#211]
Command used was `watson start myproject +flow +alteração`.

```Traceback (most recent call last):
  File "/usr/local/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.5.2', 'console_scripts', 'watson')()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/cli.py", line 154, in start
    _start(watson, project, tags)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/cli.py", line 109, in _start
    style('tags', current['tags']),
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/utils.py", line 49, in style
    return fmt(element)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/utils.py", line 26, in _style_tags
    style('tag', tag) for tag in tags
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
```

**Comment by jmaupetit** [comment]
:thinking: Hi @renatoliveira & thanks for the report! Looks like you've installed Watson _via_ `homebrew` on MacOSX. I think there might be an issue with your `locale` not supporting utf8 encoding. Can you copy/paste the output of the following command?

```bash
$ locale
```

**Comment by renatoliveira** [comment]
Hi, the output is this:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by jmaupetit** [comment]
I suppose you haven't played with locale on your machine, right?

Can you type the following commands to test if its related to your locale?

```bash
$ export LC_ALL=en_US.UTF-8
$ export LANG=en_US.UTF-8
$ watson start myproject +flow +alteração
```

If it does not fix the issue, then I will need to ask for help.

**Comment by renatoliveira** [comment]
Hi! It still happens... 😢 

```➜  ~ export LC_ALL=en_US.UTF-8
➜  ~ export LANG=en_US.UTF-8
➜  ~ watson start myproject +flow +alteração
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.5.2', 'console_scripts', 'watson')()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/cli.py", line 154, in start
    _start(watson, project, tags)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/cli.py", line 109, in _start
    style('tags', current['tags']),
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/utils.py", line 49, in style
    return fmt(element)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/watson/utils.py", line 26, in _style_tags
    style('tag', tag) for tag in tags
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)
```

**Comment by jmaupetit** [comment]
Ping @k4nar, can you help us here?

**Comment by k4nar** [comment]
I can reproduce, this is clearly a bug. I'll see if I can fix it easily.

**Comment by k4nar** [comment]
Ok, so "easily" was clearly no the right term :laughing: . But I think #212 should improve things, at least locally I wasn't seeing any more encoding error.

This is hard to fix & test that systematically in Python 2 though, so if you want to use a lot of unicode characters with Watson I would strongly advise to install it with Python 3.

**Comment by jmaupetit** [comment]
Yay, thanks.

**Comment by jmaupetit** [comment]
@renatoliveira you'll need to wait for the next (homebrew) release. Until then you can try to install Watson from the master branch.

**Comment by jmaupetit** [comment]
Not yet. I’ll keep you updated.
