### ISSUE TITLE
Traceback on wrong timestamp format in watson add

### ISSUE THREAD

**Issue by KennethNielsen** [TailorDev/Watson#247]
Hi Watson developers.

First of thanks for an amazing program and what looks like an awesome development environment.

I recently installed the development version because I needed the watson add command. When first trying it I forgot a leading 0 in the hour in a time stamp and was presented with a traceback (see below). It would probably be better with a nice error message there.

I can try and do a PR if you agree that it should be fixed.

Regards Kenneth

TRACEBACK.

```python
Traceback (most recent call last):
  File "/home/kenneth/.local/bin/watson", line 11, in <module>
    load_entry_point('td-watson', 'console_scripts', 'watson')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kenneth/.config/src/td-watson/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1469, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1790, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1438, in full_process_value
    value = self.process_value(ctx, value)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1428, in process_value
    return self.type_cast_value(ctx, value)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1417, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/core.py", line 1415, in _convert
    return self.type(value, self, ctx)
  File "/home/kenneth/.local/lib/python3.6/site-packages/click/types.py", line 39, in __call__
    return self.convert(value, param, ctx)
  File "/home/kenneth/.config/src/td-watson/watson/cli.py", line 55, in convert
    date = arrow.get(value)
  File "/home/kenneth/.local/lib/python3.6/site-packages/arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "/home/kenneth/.local/lib/python3.6/site-packages/arrow/factory.py", line 174, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/home/kenneth/.local/lib/python3.6/site-packages/arrow/parser.py", line 119, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/home/kenneth/.local/lib/python3.6/site-packages/arrow/parser.py", line 286, in _parse_multiformat
    raise ParserError('Could not match input to any of {} on \'{}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD HH:mm:ss'] on '2019-01-02 8:45:00'
```

**Comment by jmaupetit** [comment]
Thanks for the report @KennethNielsen. Everything that will improve UX would be appreciated! If you have time, feel free to fix it. Thx.
