### ISSUE TITLE
watson edit barfs with TypeError

### ISSUE THREAD

**Issue by waynew** [TailorDev/Watson#30]
Under Python 3.4.3 & arch linux, with watson installed in a venv:

    $ watson edit

<opens up vim session, simply write and quit>

:boom: 
```
Traceback (most recent call last):
  File "/home/wayne/.virtualenvs/myenv/bin/watson", line 7, in <module>
    from watson.__main__ import cli
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/watson/cli.py", line 544, in edit
    watson.frames[id] = (project, start, stop, tags)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/watson/frames.py", line 105, in __setitem__
    self._rows[self._get_index_by_id(key)] = frame
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/watson/frames.py", line 120, in _get_index_by_id
    i for i, v in enumerate(self['id']) if v.startswith(id)
  File "/home/wayne/.virtualenvs/myenv/lib/python3.4/site-packages/watson/frames.py", line 120, in <genexpr>
    i for i, v in enumerate(self['id']) if v.startswith(id)
TypeError: startswith first arg must be str or a tuple of str, not NoneType
```

**Comment by waynew** [comment]
Pinpointed the cause: 

If you look [here](https://github.com/TailorDev/Watson/blob/develop/watson/cli.py#L499-L505) you'll see that if you provide no id it will just use the previous frame if it can:

```
    if not id:
        try:
            frame = watson.frames[-1]
        except IndexError:
            raise click.ClickException(
                "No frame to edit. It's time to create your first one!"
            )
```

but it never sets the id, so when we try to [use the id](https://github.com/TailorDev/Watson/blob/develop/watson/cli.py#L544) later, it's None.

That should probably be:

    frame = watson.frames[-1]
    id = frame.id

**Comment by SpotlightKid** [comment]
Just stumbled over this too, so can I confirm the error and that the solution fixes it for me too.

Thanks for finding a solution!
