### ISSUE TITLE
AttributeError: unknown attribute: "days" in utils.get_start_time_for_period

### ISSUE THREAD

**Issue by peakBreaker** [TailorDev/Watson#301]
## Setup and reproducibility

Any details about your local setup that might be helpful in troubleshooting.
- Watson version 1.7.0
- Running Arch linux
- [My dotfiles](https://github.com/peakBreaker/.dotfiles) and [time tracking script](https://github.com/peakBreaker/.dotfiles/blob/master/.scripts/time_tracking_system/timetracker)

Detailed steps to reproduce the bug.
- Suddenly occured on my machine
- See the dockerfile in comments below

## Details

Ran into a bug while working today, using my own timetracking system built on top of watson.  However the error occurs when running `$ watson log`, or apparently any other watson command on my machine.

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.7.0', 'console_scripts', 'watson')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <module>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/utils.py", line 148, in get_start_time_for_period
    start_time = arrow.Arrow.fromdate(now.replace(days=-weekday).date())
  File "/usr/lib/python3.7/site-packages/arrow/arrow.py", line 590, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "days"
```

Changed attribute days to day in the code, according to [one resource](https://www.w3resource.com/python-exercises/arrow/python-arrow-exercise-8.php) being the correct kwarg.
`start_time = arrow.Arrow.fromdate(now.replace(day=-weekday).date())`

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.7.0', 'console_scripts', 'watson')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <module>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/utils.py", line 148, in get_start_time_for_period
    start_time = arrow.Arrow.fromdate(now.replace(day=-weekday).date())
  File "/usr/lib/python3.7/site-packages/arrow/arrow.py", line 592, in replace
    current = self._datetime.replace(**absolute_kwargs)
ValueError: day is out of range for month
```

Not sure what the `get_start_time_for_period` is supposed [to achieve](https://github.com/TailorDev/Watson/blob/e75a1a189e8606f4fe844c5d3f8f28572bf1ac50/watson/cli.py#L400).  It has no docstring, and doing the inverting of the weekday seems illogical to me (negative days?).  

Doing a [blame](https://github.com/TailorDev/Watson/blame/master/watson/utils.py#L177) I can see the code has been around for three years, and a [blame](https://github.com/TailorDev/Watson/blame/master/watson/cli.py#L399) on cli.py shows that its been used for a year.  So perhaps the arrow dependency has changed?

**Comment by peakBreaker** [comment]
## Reproducing the bug

Build and run the following dockerfile and run an arbitrary watson cli command once in the container:

```
FROM archlinux/base:latest
RUN pacman -Syu --noconfirm
RUN pacman -S tar curl sudo grep base-devel --noconfirm
RUN mkdir -p /opt/watson/
WORKDIR /opt/watson/

RUN useradd builduser -m # Create the builduser
RUN usermod -aG root builduser
RUN passwd -d builduser # Delete the buildusers password
RUN printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
RUN curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
RUN tar -xvf yay.tar.gz
RUN ls
RUN chown -R builduser ./
USER builduser
RUN cd yay && makepkg --noconfirm -si
RUN yay -Syu --noconfirm watson

ENTRYPOINT /bin/bash
```

On your machine:
```
$ docker build . -t archwatson:dirty &&  docker run --rm -it archwatson:dirty
```

Running an arbitrary watson command will give you the stacktrace

**Comment by FreddieChopin** [comment]
Same here, started occurring after full system update yesterday. Some of the packages which were updated are:
```
[2019-08-12 19:44] [ALPM] upgraded python (3.7.3-1 -> 3.7.4-1)
[2019-08-12 19:46] [ALPM] upgraded python-arrow (0.14.2-1 -> 0.14.5-1)
```

Stack trace is basically identical.

```
watson start ABC +def
Traceback (most recent call last):
  File "/usr/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.7.0', 'console_scripts', 'watson')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <module>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/cli.py", line 364, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/usr/lib/python3.7/site-packages/watson/utils.py", line 148, in get_start_time_for_period
    start_time = arrow.Arrow.fromdate(now.replace(days=-weekday).date())
  File "/usr/lib/python3.7/site-packages/arrow/arrow.py", line 590, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "days"
```

**Comment by peakBreaker** [comment]
Can confirm @FreddieChopin observation.  I downgraded arrow to 0.13.0 just now, and watson is working again:

```
$ pip uninstall arrow
$ pip install --user arrow==0.13.0
```

**Comment by jmaupetit** [comment]
Thanks for the report @peakBreaker :pray: Thanks to @davidag it will be soon fixed!

**Comment by davidag** [comment]
Fixed after @jmaupetit merge of #300 :tada:

**Comment by FreddieChopin** [comment]
Any chance for a release with the fix?

**Comment by jmaupetit** [comment]
I was expecting that :joy:

**Comment by davidag** [comment]
@jmaupetit If there's any way I can help with the release, just let me know.

There are a couple things that could be pushed forward to have them merged before releasing (PR #294 and #275 doc -I got this-).

**Comment by jmaupetit** [comment]
I think we can safely release the `1.8.0` version with the current `master` branch state. I'll handle it.

**Comment by jmaupetit** [comment]
@FreddieChopin `td-watson==1.8.0` is now available on PyPI!

**Comment by davidag** [comment]
@jmaupetit It seems that the docs are not updated in https://tailordev.github.io/Watson/

**Comment by jmaupetit** [comment]
True. Something is broken and I had no time to investigate. But AFAICS in #304 you've fixed it! :clap:
