### ISSUE TITLE
python update

### ISSUE THREAD

**Issue by sushib** [TailorDev/Watson#423]
<img width="750" alt="Screenshot 2021-04-13 at 23 10 23" src="https://user-images.githubusercontent.com/25755563/114621871-8899fb00-9cad-11eb-93be-7f08036308c5.png">

not working

**Comment by jmaupetit** [comment]
Looks like a conflict with the arrow library release. Which version of Watson are you running?

**Comment by sushib** [comment]
How could I get the version?

**Comment by jmaupetit** [comment]
Try to re-install Watson:

```
pip install --upgrade td-watson
```

**Comment by sushib** [comment]
Last login: Tue May 11 12:04:17 on ttys000
(base) ***@***.***Phone-de-lugos ~ % pip install --upgrade td-watson
Requirement already satisfied: td-watson in ./opt/anaconda3/lib/python3.8/site-packages (2.0.0)
Collecting td-watson
  Downloading td_watson-2.0.1-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: click-didyoumean in ./opt/anaconda3/lib/python3.8/site-packages (from td-watson) (0.0.3)
Requirement already satisfied: arrow>=1.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from td-watson) (1.0.3)
Requirement already satisfied: click>=7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from td-watson) (7.1.2)
Requirement already satisfied: requests in ./opt/anaconda3/lib/python3.8/site-packages (from td-watson) (2.25.1)
Requirement already satisfied: python-dateutil>=2.7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from arrow>=1.0.0->td-watson) (2.8.1)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.0->arrow>=1.0.0->td-watson) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->td-watson) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->td-watson) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->td-watson) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->td-watson) (2020.12.5)
Installing collected packages: td-watson
  Attempting uninstall: td-watson
    Found existing installation: td-watson 2.0.0
    Uninstalling td-watson-2.0.0:
      Successfully uninstalled td-watson-2.0.0
Successfully installed td-watson-2.0.1

(base) ***@***.***Phone-de-lugos ~ % watson
Traceback (most recent call last):
  File "/Users/bruno/opt/anaconda3/bin/watson", line 5, in <module>
    from watson.__main__ import cli
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/watson/__main__.py", line 1, in <module>
    from watson import cli
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/watson/cli.py", line 455, in <module>
    _SHORTCUT_OPTIONS_VALUES = {
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/watson/cli.py", line 456, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/watson/utils.py", line 177, in get_start_time_for_period
    start_time = get_last_full_moon(now)
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/watson/fullmoon.py", line 225, in get_last_full_moon
    now = d.int_timestamp
  File "/Users/bruno/opt/anaconda3/lib/python3.8/site-packages/arrow/arrow.py", line 418, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Arrow' object has no attribute 'int_timestamp'
(base) ***@***.***Phone-de-lugos ~ %

**Comment by jmaupetit** [comment]
Have you tried to uninstall Arrow and force Watson re-install to ensure the appropriate Arrow release is in use?

```
pip uninstall arrow && pip install --force-reinstall td-watson
```

**Comment by sushib** [comment]
It works! 

Good job

Bruno
