### ISSUE TITLE
Crash caused by (?) fullmoon.py

### ISSUE THREAD

**Issue by ab2422** [TailorDev/Watson#424]
I'm running Python v3.9.2-1, and python-arrow v1.0.3-1. I get the following error when trying to run any watson command. Looks like in fullmoon.py, line 226 should call method now() instead of just now?

Here is the error message:
```
Traceback (most recent call last):
  File "/home/annab/.local/bin/watson", line 5, in <module>
    from watson.__main__ import cli
  File "/home/annab/.local/lib/python3.9/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli
  File "/home/annab/.local/lib/python3.9/site-packages/watson/cli.py", line 441, in <module>
    _SHORTCUT_OPTIONS_VALUES = {
  File "/home/annab/.local/lib/python3.9/site-packages/watson/cli.py", line 442, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS
  File "/home/annab/.local/lib/python3.9/site-packages/watson/utils.py", line 193, in get_start_time_for_period
    start_time = get_last_full_moon(now)
  File "/home/annab/.local/lib/python3.9/site-packages/watson/fullmoon.py", line 226, in get_last_full_moon
    idx = bisect.bisect_right(fullmoons, now)
TypeError: '<' not supported between instances of 'method' and 'int'
```

**Comment by ab2422** [comment]
Follow up: on my machine at least I can fix the issue by two small fixes, one in fullmoons.py (a missing call to the method, though a few lines above what I thought when I posted above), and one in cli.py (in arrow, should change the timezone via the "to" method instead of just setting tzinfo directly). I will now try to actually implement these changes.

**Comment by ab2422** [comment]
NVM, turns out the issue is just that the AUR package is one commit behind the current. Issue resolved!
