### ISSUE TITLE
Cannot start watson anymore

### ISSUE THREAD

**Issue by lepokle** [TailorDev/Watson#434]
Any time I call watson, regardless of the arguments, I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/watson", line 33, in <module>
    sys.exit(load_entry_point('td-watson==2.0.1', 'console_scripts', 'watson')())
  File "/usr/bin/watson", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/watson/__main__.py", line 1, in <module>
    from watson import cli
  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 529, in <module>
    def report(watson, current, from_, to, projects, tags, ignore_projects,
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 46, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2108, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

I'm running Arch Linux with all updates applied. I suggest that one of the updates broke it, but I'm not able to determine the exact cause of the problem.

Package info:
```
Name            : watson
Version         : 2.0.1-1
Description     : A wonderful CLI to track your time!
Architecture    : any
URL             : https://tailordev.github.io/Watson/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  python-arrow  python-click  python-click-didyoumean  python-requests
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 330,00 KiB
Packager        : Unknown Packager
Build Date      : Do 27 Mai 2021 20:39:43 CEST
Install Date    : Do 27 Mai 2021 20:39:52 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

Name            : python
Version         : 3.9.5-3
Description     : Next generation of the python high-level scripting language
Architecture    : x86_64
URL             : https://www.python.org/
Licenses        : custom
Groups          : None
Provides        : python3
Depends On      : bzip2  expat  gdbm  libffi  libnsl  libxcrypt  openssl  zlib
Optional Deps   : python-setuptools [installed]
                  python-pip [installed]
                  sqlite [installed]
                  mpdecimal: for decimal
                  xz: for lzma [installed]
                  tk: for tkinter [installed]
Required By     : ansible  ansible-core  ansible-lint  apm  asciidoc  autojump  bind  cython  distcc  fontforge  gconf  gdb  gdb-common
                  geany-plugins  glslang  gscreenshot  gstreamer  inkscape  intellij-idea-community-edition  iotop  itstool  ktoblzcheck  libixion
                  libreoffice-fresh  lxc  mallard-ducktype  med  mercurial  miraclecast  mono  namcap  nightshift  node-gyp  ocrmypdf  pahole
                  pcsclite  photofilmstrip  py3status  pyalpm  python-apipkg  python-appdirs  python-apsw  python-argcomplete  python-argh
                  python-asgiref  python-asn1crypto  python-atomicwrites  python-attrs  python-babel  python-beaker  python-blinker  python-brotli
                  python-cached-property  python-cairo  python-cchardet  python-certifi  python-chardet  python-click  python-colorama
                  python-coloredlogs  python-configargparse  python-construct  python-contextlib2  python-css-parser  python-cssselect
                  python-cssutils  python-decorator  python-defusedxml  python-discid  python-distlib  python-distro  python-dnspython
                  python-docopt  python-docutils  python-editorconfig  python-evdev  python-fastimport  python-fonttools  python-future
                  python-gmusicapi-git  python-gobject  python-gpsoauth  python-h11  python-hpack  python-httplib2  python-humanfriendly
                  python-hyperframe  python-idna  python-ifaddr  python-imagesize  python-iniconfig  python-itsdangerous  python-jellyfish
                  python-kaitaistruct  python-kiwisolver  python-lazy-object-proxy  python-lockfile  python-lxml  python-markdown  python-markupsafe
                  python-mccabe  python-mechanicalsoup  python-mock  python-monotonic  python-more-itertools  python-mpd2  python-msgpack
                  python-munkres  python-musicbrainzngs  python-netifaces  python-nose  python-numpy  python-olefile  python-ordered-set
                  python-passlib  python-pathtools  python-patiencediff  python-pexpect  python-pillow  python-pivy  python-ply  python-proboscis
                  python-progress  python-protobuf  python-psutil  python-psycopg2  python-ptyprocess  python-publicsuffix2  python-pyacoustid
                  python-pyasn1  python-pychm  python-pycryptodome  python-pycryptodomex  python-pycups  python-pycurl  python-pyelftools
                  python-pyicu  python-pynacl  python-pyopenssl  python-pyparsing  python-pypdf  python-pypdf2  python-pyperclip  python-pyproj
                  python-pypubsub  python-pyqt5-sip  python-pyserial  python-pystache  python-pytoml  python-pytz  python-pyxdg  python-qtpy
                  python-regex  python-reportlab  python-resolvelib  python-ruamel.yaml.clib  python-setproctitle  python-sgmllib  python-shiboken2
                  python-sip-pyqt5  python-sip4  python-six  python-smmap  python-snowballstemmer  python-sortedcontainers  python-soupsieve
                  python-sphinx-alabaster-theme  python-sqlalchemy  python-texttable  python-toml  python-tornado  python-tqdm  python-typed-ast
                  python-typing_extensions  python-unidecode  python-unrardll  python-urllib3  python-urwid  python-validictory  python-wcwidth
                  python-webencodings  python-werkzeug  python-whoosh  python-wrapt  python-xmltodict  python-yaml  python-zeroconf  python-zipp
                  python-zope-event  python-zope-interface  python-zstandard  scons  scribus  setconf  smbclient  smem  steam  virtualbox  watson
                  widelands
Optional For    : boost  botan  brltty  btrfs-progs  clang  evemu  git  glib2  graphviz  gtest  gtk2  gupnp  i2c-tools  imath  ki18n  ldb  lensfun
                  libbytesize  libevent  libftdi  libieee1284  libnewt  libproxy  libpwquality  lilv  lirc  mlt6  net-snmp  nfs-utils  postgresql
                  postgresql-old-upgrade  rrdtool  subversion  talloc  tdb  tevent  texlive-core  usbutils  util-linux  vim  vim-runtime  volume_key
                  vtk  xfsprogs  zbar  zfs-utils
Conflicts With  : None
Replaces        : python3
Installed Size  : 76,05 MiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Mo 24 Mai 2021 14:50:35 CEST
Install Date    : Fr 28 Mai 2021 16:35:14 CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

Any help would be appreciated.

Thanks.

**Comment by Kevin-Mok** [comment]
I'm running into the same issue on Arch as well with 2.0.1, but when I clone the repository and run it in a virtual environment using my own data, it seems to work fine. :thinking:

**Comment by lepokle** [comment]
Downgrading python-click (from https://archive.archlinux.org/packages/p/python-click/) fixed it for me for now.
Since the final fix is already in development tracked by #432 , I'm closing this issue here.
