### ISSUE TITLE
Watson fails to start

### ISSUE THREAD

**Issue by d4ve02** [TailorDev/Watson#440]
I installed Watson 2.0.1-1 from the AUR following the installation instructions. I'm using Arch Linux 5.10.45-1-lts.

When I run watson, I get:

> Traceback (most recent call last):
  File "/usr/bin/watson", line 33, in <module>
    sys.exit(load_entry_point('td-watson==2.0.1', 'console_scripts', 'watson')())
  File "/usr/bin/watson", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/watson/__main__.py", line 1, in <module>
    from watson import cli
  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 529, in <module>
    def report(watson, current, from_, to, projects, tags, ignore_projects,
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 46, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2108, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.

I also tried installing Watson using pip instead, but I get pretty much the same error:

> Traceback (most recent call last):
  File "/home/zero/.local/bin/watson", line 5, in <module>
    from watson.__main__ import cli
  File "/home/zero/.local/lib/python3.9/site-packages/watson/__main__.py", line 1, in <module>
    from watson import cli
  File "/home/zero/.local/lib/python3.9/site-packages/watson/cli.py", line 529, in <module>
    def report(watson, current, from_, to, projects, tags, ignore_projects,
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/zero/.local/lib/python3.9/site-packages/watson/cli.py", line 46, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2108, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.

Any idea?

**Comment by d4ve02** [comment]
I tried installing the development version manually downloading the repo and installing with pip, and it works as expected.

Uninstalled the development version and installed the AUR package again, everything now works as expected. Maybe there were some issues with dependencies.

**Comment by jmaupetit** [comment]
Indeed :wink: https://github.com/TailorDev/Watson/issues/430

We'll release that soon!
