### ISSUE TITLE
ValueError: 'default' must be a list when 'multiple' is true.

### ISSUE THREAD

**Issue by mayankshukla91** [TailorDev/Watson#443]
> C:\Users\mshukla>watson
Traceback (most recent call last):
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mshukla\AppData\Local\Programs\Python\Python37-32\Scripts\watson.exe\__main__.py", line 4, in <module>
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\watson\__main__.py", line 1, in <module>
    from watson import cli
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\watson\cli.py", line 531, in <module>
    pager, aggregated=False, include_partial_frames=True):
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\watson\cli.py", line 46, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "c:\users\mshukla\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.

Facing above error when trying to run watson. Is it some library issue or my python installation issue itself ?
Python version : Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32

**Comment by kyaso** [comment]
Also getting this error on Linux (Manjaro). Python 3.9.5.

**Comment by jmaupetit** [comment]
Yup. Closing this as duplicate.

**Comment by jmaupetit** [comment]
Should be fixed with the 2.1.0 fresh release!
