### ISSUE TITLE
Possible Python dependency bug: "Parameter.__init__() got an unexpected keyword argument 'autocompletion'"

### ISSUE THREAD

**Issue by RomanHN** [TailorDev/Watson#468]
Successfully installed Watson on Manjaro Linux with `pip3 install td-watson` in my home directory. When `watson` is executed, the following error message appears:

```
Traceback (most recent call last):
  File "/home/roman/.local/bin/watson", line 5, in <module>
    from watson.__main__ import cli
  File "/home/roman/.local/lib/python3.10/site-packages/watson/__main__.py", line 1, in <module>
    from watson import cli
  File "/home/roman/.local/lib/python3.10/site-packages/watson/cli.py", line 215, in <module>
    def start(ctx, watson, confirm_new_project, confirm_new_tag, args, at_,
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 287, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 2947, in __init__
    super().__init__(param_decls, required=required, **attrs)
TypeError: Parameter.__init__() got an unexpected keyword argument 'autocompletion'
```

Tried installing Watson in a Python `venv` environment, but the same error came up. Also tried looking into the code for `/click/core.py`, but I don't know where to start or how to debug this kind of issue. Let me know if you need any other information or if I'm doing something wrong.

**Comment by jmaupetit** [comment]
I think it should be fixed using the recent 2.1.0 release!
