### ISSUE TITLE
watson log fails

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#6]
When you try to log previous activity, watson fails. To reproduce test:

    $ watson log

The traceback for python3.4 installed via homebrew (MacOS 10.10.2) follows:

```
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 9, in <module>
    load_entry_point('watson==0.1', 'console_scripts', 'watson')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/watson-0.1-py3.4.egg/watson/__main__.py", line 3, in <module>
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/watson-0.1-py3.4.egg/watson/cli.py", line 278, in log
ValueError: max() arg is an empty sequence
```

**Comment by jmaupetit** [comment]
It occurs with stored frames with no tags.

**Comment by k4nar** [comment]
That's why we need #5 :) .
